### PR TITLE
BF: use consistent shebang and executable bit for scripts

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
it seems that tests weren't ran for a while since there were no activity since a while, so I don't think it is my PR to blame (at least not for all problems ;) ). I wish those error msgs were a bit more descriptive (e.g. include stdout/stderr of the failed command)

**Comment by thperret** [comment]
Thanks for your feedback on that.

I agree with you about the tests, I think the problem comes from a dependency package update that we didn't account for. I'll check that on the next PR we'll do in the following days. It will be a big update because we improved a lot of parts in the VEM algorithm.

Concerning the shebang, it's true that we should use consistent one for each command line. But I think that we should use `#!/usr/bin/env python2` to force the system to choose for python version 2. In some distribution (Arch Linux is the only one that came to mind) the default interpreter for python is the version 3, it is also possible that some main distributions will change their default behavior in the future.

Thanks again for this PR that I'll include in the next update.

**Comment by yarikoptic** [comment]
shebang -- first I thought that it would fail for me in virtualenvs having only python... but it seems that at least on debian virtualenv does create venv/bin/python2 so should generally work "for me".  Although I am not sure if such a practice is anyhow widely accepted or even recommended.

**Comment by thperret** [comment]
According to the [PEP394](https://www.python.org/dev/peps/pep-0394/), python2 should always exists and point to the version 2.x of python (as python3 should point to version 3.y). I think it's the case of all unix-like systems (even Mac OS). As we're not supporting MS Windows (for now) I think the shebing I proposed should always work.

**Comment by yarikoptic** [comment]
Forgot about that pep, so indeed it should.

**Comment by thperret** [comment]
will be included in next PR

**Pull request closed without merging**
